package com.agro.trace.common.domain;

public enum LotStatus {
    CREATED,
    ACCEPTED,
    AT_NODAL_CENTER,
    PACKAGED,
    IN_TRANSIT,
    AT_SUPPLIER,
    TESTING,
    TEST_PASSED,
    TEST_FAILED,
    AT_MANUFACTURER,
    PROCESSED,
    MANUFACTURER_TEST_PASSED,
    MANUFACTURER_TEST_FAILED,
    BUNDLED,
    AT_DISTRIBUTOR,
    DISTRIBUTOR_VERIFIED,
    AT_RETAILER,
    READY_FOR_SALE,
    SOLD,
    QUARANTINED,
    REJECTED,
    RECALLED,
    SUSPENDED
}