export const supplyChainABI = [

  {
    "type": "event",
    "name": "RequestCreated",
    "inputs": [
      { "indexed": true, "name": "requestId", "type": "uint256" },
      { "indexed": true, "name": "farmer", "type": "address" },
      { "indexed": false, "name": "materialName", "type": "string" },
      { "indexed": false, "name": "quantity", "type": "uint256" },
    ],
  },
  {
    "type": "event",
    "name": "RequestDeleted",
    "inputs": [
      { "indexed": true, "name": "requestId", "type": "uint256" },
      { "indexed": true, "name": "farmer", "type": "address" },
    ],
  },
  {
    "type": "event",
    "name": "RawBatchCreated",
    "inputs": [
      { "indexed": true, "name": "rawBatchId", "type": "uint256" },
      { "indexed": true, "name": "requestId", "type": "uint256" },
      { "indexed": true, "name": "farmer", "type": "address" },
      { "indexed": false, "name": "supplier", "type": "address" },
    ],
  },
  {
    "type": "event",
    "name": "FarmerToSupplierTransferred",
    "inputs": [
      { "indexed": true, "name": "rawBatchId", "type": "uint256" },
      { "indexed": true, "name": "farmer", "type": "address" },
      { "indexed": true, "name": "supplier", "type": "address" },
    ],
  },
  {
    "type": "event",
    "name": "SupplierToManufacturerTransferred",
    "inputs": [
      { "indexed": true, "name": "rawBatchId", "type": "uint256" },
      { "indexed": true, "name": "supplier", "type": "address" },
      { "indexed": true, "name": "manufacturer", "type": "address" },
    ],
  },
  {
    "type": "event",
    "name": "ManufacturerInspectionRecorded",
    "inputs": [
      { "indexed": true, "name": "inspectionId", "type": "uint256" },
      { "indexed": true, "name": "rawBatchId", "type": "uint256" },
      { "indexed": true, "name": "manufacturer", "type": "address" },
      { "indexed": false, "name": "result", "type": "string" },
    ],
  },
  {
    "type": "event",
    "name": "ManufacturedBatchCreated",
    "inputs": [
      { "indexed": true, "name": "manufacturedBatchId", "type": "uint256" },
      { "indexed": true, "name": "manufacturer", "type": "address" },
      { "indexed": false, "name": "productName", "type": "string" },
      { "indexed": false, "name": "quantity", "type": "uint256" },
    ],
  },
  {
    "type": "event",
    "name": "ManufacturerToDistributorTransferred",
    "inputs": [
      { "indexed": true, "name": "manufacturedBatchId", "type": "uint256" },
      { "indexed": true, "name": "manufacturer", "type": "address" },
      { "indexed": true, "name": "distributor", "type": "address" },
    ],
  },
  {
    "type": "event",
    "name": "RetailerAllocationCreated",
    "inputs": [
      { "indexed": true, "name": "allocationId", "type": "uint256" },
      { "indexed": true, "name": "manufacturedBatchId", "type": "uint256" },
      { "indexed": true, "name": "retailer", "type": "address" },
      { "indexed": false, "name": "distributor", "type": "address" },
      { "indexed": false, "name": "quantity", "type": "uint256" },
    ],
  },
  {
    "type": "event",
    "name": "AuthorityInspectionRecorded",
    "inputs": [
      { "indexed": true, "name": "inspectionId", "type": "uint256" },
      { "indexed": true, "name": "requestId", "type": "uint256" },
      { "indexed": true, "name": "authority", "type": "address" },
      { "indexed": false, "name": "result", "type": "string" },
    ],
  },
  {
    "type": "event",
    "name": "ProductRecalled",
    "inputs": [
      { "indexed": true, "name": "manufacturedBatchId", "type": "uint256" },
      { "indexed": true, "name": "manufacturer", "type": "address" },
      { "indexed": false, "name": "reason", "type": "string" },
    ],
  },

  {
    "type": "function",
    "name": "createRequest",
    "stateMutability": "nonpayable",
    "inputs": [
      { "name": "materialName", "type": "string" },
      { "name": "quantity", "type": "uint256" },
      { "name": "metadata", "type": "string" },
    ],
    "outputs": [{ "name": "", "type": "uint256" }],
  },
  {
    "type": "function",
    "name": "deleteRequest",
    "stateMutability": "nonpayable",
    "inputs": [{ "name": "requestId", "type": "uint256" }],
    "outputs": [],
  },
  {
    "type": "function",
    "name": "farmerToSupplier",
    "stateMutability": "nonpayable",
    "inputs": [
      { "name": "requestId", "type": "uint256" },
      { "name": "supplier", "type": "address" },
    ],
    "outputs": [{ "name": "", "type": "uint256" }],
  },
  {
    "type": "function",
    "name": "supplierToManufacturer",
    "stateMutability": "nonpayable",
    "inputs": [
      { "name": "rawBatchIds", "type": "uint256[]" },
      { "name": "manufacturer", "type": "address" },
    ],
    "outputs": [],
  },
  {
    "type": "function",
    "name": "recordManufacturerInspection",
    "stateMutability": "nonpayable",
    "inputs": [
      { "name": "rawBatchId", "type": "uint256" },
      { "name": "result", "type": "string" },
      { "name": "metadata", "type": "string" },
    ],
    "outputs": [{ "name": "", "type": "uint256" }],
  },
  {
    "type": "function",
    "name": "createManufacturedBatch",
    "stateMutability": "nonpayable",
    "inputs": [
      { "name": "rawBatchIds", "type": "uint256[]" },
      { "name": "productName", "type": "string" },
      { "name": "quantity", "type": "uint256" },
    ],
    "outputs": [{ "name": "", "type": "uint256" }],
  },
  {
    "type": "function",
    "name": "manufacturerToDistributor",
    "stateMutability": "nonpayable",
    "inputs": [
      { "name": "manufacturedBatchId", "type": "uint256" },
      { "name": "distributor", "type": "address" },
    ],
    "outputs": [],
  },
  {
    "type": "function",
    "name": "distributorToRetailer",
    "stateMutability": "nonpayable",
    "inputs": [
      { "name": "manufacturedBatchId", "type": "uint256" },
      { "name": "retailer", "type": "address" },
      { "name": "quantity", "type": "uint256" },
    ],
    "outputs": [{ "name": "", "type": "uint256" }],
  },
  {
    "type": "function",
    "name": "recordAuthorityInspection",
    "stateMutability": "nonpayable",
    "inputs": [
      { "name": "requestId", "type": "uint256" },
      { "name": "result", "type": "string" },
      { "name": "metadata", "type": "string" },
    ],
    "outputs": [{ "name": "", "type": "uint256" }],
  },
  {
    "type": "function",
    "name": "recallProduct",
    "stateMutability": "nonpayable",
    "inputs": [
      { "name": "manufacturedBatchId", "type": "uint256" },
      { "name": "reason", "type": "string" },
    ],
    "outputs": [],
  },

  {
    "type": "function",
    "name": "getRequest",
    "stateMutability": "view",
    "inputs": [{ "name": "requestId", "type": "uint256" }],
    "outputs": [
      { "name": "", "type": "uint256" },
      { "name": "", "type": "address" },
      { "name": "", "type": "string" },
      { "name": "", "type": "uint256" },
      { "name": "", "type": "string" },
      { "name": "", "type": "bool" },
      { "name": "", "type": "uint256" },
    ],
  },
  {
    "type": "function",
    "name": "getRequestCount",
    "stateMutability": "view",
    "inputs": [],
    "outputs": [{ "name": "", "type": "uint256" }],
  },
  {
    "type": "function",
    "name": "getRawBatch",
    "stateMutability": "view",
    "inputs": [{ "name": "rawBatchId", "type": "uint256" }],
    "outputs": [
      { "name": "", "type": "uint256" },
      { "name": "", "type": "uint256" },
      { "name": "", "type": "address" },
      { "name": "", "type": "address" },
      { "name": "", "type": "string" },
      { "name": "", "type": "uint256" },
      { "name": "", "type": "bool" },
      { "name": "", "type": "uint256" },
      { "name": "", "type": "bool" },
    ],
  },
  {
    "type": "function",
    "name": "getRawBatchCount",
    "stateMutability": "view",
    "inputs": [],
    "outputs": [{ "name": "", "type": "uint256" }],
  },
  {
    "type": "function",
    "name": "getManufacturedBatch",
    "stateMutability": "view",
    "inputs": [{ "name": "manufacturedBatchId", "type": "uint256" }],
    "outputs": [
      { "name": "", "type": "uint256" },
      { "name": "", "type": "string" },
      { "name": "", "type": "uint256" },
      { "name": "", "type": "uint256" },
      { "name": "", "type": "address" },
      { "name": "", "type": "address" },
      { "name": "", "type": "bool" },
      { "name": "", "type": "bool" },
    ],
  },
  {
    "type": "function",
    "name": "getManufacturedBatchCount",
    "stateMutability": "view",
    "inputs": [],
    "outputs": [{ "name": "", "type": "uint256" }],
  },
  {
    "type": "function",
    "name": "getRetailerAllocation",
    "stateMutability": "view",
    "inputs": [{ "name": "allocationId", "type": "uint256" }],
    "outputs": [
      { "name": "", "type": "uint256" },
      { "name": "", "type": "uint256" },
      { "name": "", "type": "address" },
      { "name": "", "type": "address" },
      { "name": "", "type": "uint256" },
      { "name": "", "type": "uint256" },
    ],
  },
  {
    "type": "function",
    "name": "getRetailerAllocationCount",
    "stateMutability": "view",
    "inputs": [],
    "outputs": [{ "name": "", "type": "uint256" }],
  },
  {
    "type": "function",
    "name": "getSourceRawBatches",
    "stateMutability": "view",
    "inputs": [{ "name": "manufacturedBatchId", "type": "uint256" }],
    "outputs": [{ "name": "", "type": "uint256[]" }],
  },
  {
    "type": "function",
    "name": "getBatchManufacturerInspections",
    "stateMutability": "view",
    "inputs": [{ "name": "rawBatchId", "type": "uint256" }],
    "outputs": [{ "name": "", "type": "uint256[]" }],
  },
  {
    "type": "function",
    "name": "getBatchRetailerAllocations",
    "stateMutability": "view",
    "inputs": [{ "name": "manufacturedBatchId", "type": "uint256" }],
    "outputs": [{ "name": "", "type": "uint256[]" }],
  },
  {
    "type": "function",
    "name": "getManufacturerInspection",
    "stateMutability": "view",
    "inputs": [{ "name": "inspectionId", "type": "uint256" }],
    "outputs": [
      { "name": "", "type": "uint256" },
      { "name": "", "type": "uint256" },
      { "name": "", "type": "address" },
      { "name": "", "type": "string" },
      { "name": "", "type": "string" },
      { "name": "", "type": "uint256" },
    ],
  },
  {
    "type": "function",
    "name": "getAuthorityInspection",
    "stateMutability": "view",
    "inputs": [{ "name": "inspectionId", "type": "uint256" }],
    "outputs": [
      { "name": "", "type": "uint256" },
      { "name": "", "type": "uint256" },
      { "name": "", "type": "address" },
      { "name": "", "type": "string" },
      { "name": "", "type": "string" },
      { "name": "", "type": "uint256" },
    ],
  },
  {
    "type": "function",
    "name": "getRawBatchManufacturedBatches",
    "stateMutability": "view",
    "inputs": [{ "name": "rawBatchId", "type": "uint256" }],
    "outputs": [{ "name": "", "type": "uint256[]" }],
  },
  {
    "type": "function",
    "name": "getRequestAuthorityInspections",
    "stateMutability": "view",
    "inputs": [{ "name": "requestId", "type": "uint256" }],
    "outputs": [{ "name": "", "type": "uint256[]" }],
  },
] as const;
